### ISSUE TITLE
Pretrained network?

### ISSUE THREAD

**Issue by collinabidi** [dgominski/generalizablersc#2]
Hi there, would it be possible to provide a pretrained network? I can train on a couple of the datasets but unfortunately my GPU cannot fit everything into memory. I'd like to test on a satellite dataset that my lab has collected from the ISS (https://caspr.space/) and share the results.

**Comment by dgominski** [comment]
Here is a link to a pretrained ResNet-50 model trained on all datasets except WHU-RS19:
https://drive.google.com/drive/folders/1DFf-HuZkhaJACvDcJlvonrIv9ev5L8zP?usp=sharing

it should load without problem with the --load-from option pointing to a folder containing those two .pth files.
With it I have ~95% accuracy for 5-shot on WHU-RS19.
